# _config.yml
title: "Your Name - Portfolio"
description: "Personal portfolio showcasing my projects and skills"
theme: jekyll-theme-cayman
baseurl: ""
url: "https://PamudiHansani.github.io"

# Optional social links
twitter_username: yourtwitter
github_username: akindu-indu

# Build settings
markdown: kramdown
permalink :Â pretty
